{{- if or (eq "true" (get .Values.global.serviceAccount "create"|toString)) (empty (get .Values.global.serviceAccount "create"|toString))}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "general.sa_name" . }}
  labels:
    {{- include "general.labels" . | nindent 4 }}
  {{- with .Values.global.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}