apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "general.sa_name" . }}
  labels:
    {{- include "general.labels" . | nindent 4 }}
  {{- with .Values.global.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
